global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: 'Prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'Telegraf'
    scrape_interval: 10s
    static_configs:
      - targets: ['telegraf:8125']

  - job_name: 'HP2016'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.50.10:9414']

  - job_name: 'HP2023'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.50.11:9414']