# https://grafana.com/docs/loki/latest/clients/promtail/configuration/
# https://docs.docker.com/engine/api/v1.41/#operation/ContainerList
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
# - job_name: flog_scrape
#   docker_sd_configs:
#     - host: unix:///var/run/docker.sock
#       refresh_interval: 5s
#      filter:
#        - name: label
#          values: ["logging=promtail"]
#   relabel_configs:
#     - source_labels: ['__meta_docker_container_name']
#       regex: '/(.*)'
#       target_label: 'container'      
#     - source_labels: ['__meta_docker_container_log_stream']
#       target_label: 'logstream'
#     - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
#       target_label: 'stack'
#     - source_labels: ['__meta_docker_network_name']
#       target_label: 'network'
#     - source_labels: ['__meta_docker_container_name']
#       regex: '/(.*)\.[0-9]\..*'
#       target_label: 'name'      
#   pipeline_stages:
#     - docker: {}
#     - static_labels:
#         job: dockerlog
#     - timestamp:
#       format: RFC3339Nano
#       source: time

- job_name: syslog
  syslog:
    listen_address: 0.0.0.0:1514 # make sure you also expose this port on the container
    idle_timeout: 60s
    label_structured_data: no
    labels:
      job: "syslog"
  relabel_configs:
  - source_labels: ['__syslog_message_hostname']
    target_label: 'host'
    
  - source_labels: ['__syslog_message_app_name']
    target_label: 'app_name'
    
  - source_labels: ['__syslog_message_proc_id']
    target_label: 'proc_id'
    
  - source_labels: ['__syslog_message_msg_id']
    target_label: 'msg_id'
    
  - source_labels: ['__syslog_connection_ip_address']
    target_label: 'ip_address'
    
  - source_labels: ['__syslog_connection_hostname']
    target_label: 'hostname'
    
  - source_labels: ['__syslog_message_severity']
    target_label: 'severity'
    
  - source_labels: ['__syslog_message_facility']
    target_label: 'facility'
  # pipeline_stages:
  #   - match:
  #       selector: '{job="syslog"}' #match all
  #       stages:
  #         - pack:
  #             labels:
  #               - proc_id
  #               - msg_id
  #               - ip_address
  #               - hostname
  #               - severity
  #               - facility
